sonar.projectKey=jest-sonarqube
sonar.projectName=jest-sonarqube
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src
sonar.inclusions=src/**/*.ts,src/**/*.tsx
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/setupTests.ts,src/main.tsx,node_modules/**,dist/**,coverage/**
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx

sonar.host.url=https://potential-happiness-979x46rqjrx4f946-9000.app.github.dev
# Pass token via env: 
SONAR_TOKEN=sqp_4404a37661d09c66aaa6c30e019c4b7ff4d86e10

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
